# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3043e2d81b4ef416a3a69eaf01b533b4967aa513cec9d7b88dc2b73bb29dc2c17368a461d4d66b6eb0e5937dc1cf240c3d20de010772b1c8186ed87832e16061

test:
  secret_key_base: 4a2a7e9ddb92c350e5b13d38c7cca2e8ef61f0e0415330508b96baea2eca5afee1884ecd63b96b73c52d315bb57ed3cc368d5dda21ed45463f71bd7fd9b1bd09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
